#Abilities Configuration
#
#morph-time is how long you can stay morphed as a certain mob - set to 0 to disable
#morph-cooldown is how often you can morph back into the mob after unmorphing from that particular mob - set to 0 to disable
#ability-cooldown is the cooldown on the given ability of the mob - set to 0 to disable
#
#Enable flying?
flying: true

horse:
  morph-time: 0
  morph-cooldown: 0
  speed: true
wolf:
  morph-time: 0
  morph-cooldown: 0
ocelot:
  morph-time: 0
  morph-cooldown: 0
  speed: true
cow:
  morph-time: 0
  morph-cooldown: 0
pig:
  morph-time: 0
  morph-cooldown: 0
wither_skeleton:
  morph-time: 0
  morph-cooldown: 0
  ability-cooldown: 0
bat:
  morph-time: 0
  morph-cooldown: 0
blaze:
  morph-time: 0
  morph-cooldown: 0
  fire: true
  ability-cooldown: 5
cave_spider:
  morph-time: 0
  morph-cooldown: 0
  spider-climb: true
  ability-cooldown: 0
chicken:
  morph-time: 0
  morph-cooldown: 0
  egg: true
  ability-cooldown: 120
creeper:
  morph-time: 0
  morph-cooldown: 0
  explosion: true
  explosion-damage: false
enderman:
  morph-time: 0
  morph-cooldown: 0
  teleport: true
  ability-cooldown: 5
endermite:
  morph-time: 0
  morph-cooldown: 0
ghast:
  morph-time: 0
  morph-cooldown: 0
  fireball: true
  ability-cooldown: 5
guardian:
  morph-time: 0
  waterbreathing: true
  morph-cooldown: 0
iron_golem:
  morph-time: 0
  morph-cooldown: 0
  strength: true
magma_cube:
  morph-time: 0
  morph-cooldown: 0
mushroom_cow:
  morph-time: 0
  morph-cooldown: 0
pig_zombie:
  morph-time: 0
  morph-cooldown: 0
  eat: true
  speed: true
sheep:
  morph-time: 0
  morph-cooldown: 0
silverfish:
  morph-time: 0
  morph-cooldown: 0
skeleton:
  morph-time: 0
  morph-cooldown: 0
  shoot: true
slime:
  morph-time: 0
  morph-cooldown: 0
  jump-boost: true
  split: true
snowman:
  morph-time: 0
  morph-cooldown: 0
  snow: true
  shoot: true
  ability-cooldown: 0
spider:
  morph-time: 0
  morph-cooldown: 0
  climb: true
  web: true
  #Remove spider webs after they are shot?
  removeSpiderWeb: true
  #How long (seconds) should webs stay for before despawning
  spiderWebRemove: 30
  ability-cooldown: 0
squid:
  morph-time: 0
  morph-cooldown: 0
  waterbreathing: true
villager:
  morph-time: 0
  morph-cooldown: 0
witch:
  morph-time: 0
  morph-cooldown: 0
wither:
  morph-time: 0
  morph-cooldown: 0
llama:
  morph-time: 0
  morph-cooldown: 0
  spit: true
  ability-cooldown: 0
vex:
  morph-time: 0
  morph-cooldown: 0
  phase: true
  #The amount of blocks vex can phase through
  max-layers: 2
  ability-cooldown: 30
vindicator:
  morph-time: 0
  morph-cooldown: 0
evoker:
  morph-time: 0
  morph-cooldown: 0
  attack: true
  spawnVex: true
  attack-cooldown: 5
  spawnVex-cooldown: 30
zombie:
  morph-time: 0
  morph-cooldown: 0
  eat: true
rabbit:
  morph-time: 0
  morph-cooldown: 0
  jump-boost: true
giant:
  morph-time: 0
  enabled: true
  morph-cooldown: 0
  throw: true
  #This increases how high giants can throw people
  force: 2
  #Enables the giant to 'throw' blocks as he walks
  #NOTE: This might cause random blocks to be placed/broken if enabled
  walk-throw: false
  ability-cooldown: 0
enderdragon:
  morph-time: 0
  enabled: true
  morph-cooldown: 0
  fireball: true
  ability-cooldown: 0
mule:
  morph-time: 0
  morph-cooldown: 0
donkey:
  morph-time: 0
  morph-cooldown: 0
zombie_villager:
  morph-time: 0
  morph-cooldown: 0
parrot:
  morph-time: 0
  morph-cooldown: 0
illusioner:
  morph-time: 0
  morph-cooldown: 0
  ability-cooldown: 0
stray:
  morph-time: 0
  morph-cooldown: 0
  slow: true
  shoot: true
  ability-cooldown: 0
husk:
  morph-time: 0
  morph-cooldown: 0
  hunger: true
dolphin:
  morph-time: 0
  morph-cooldown: 0
drowned:
  morph-time: 0
  morph-cooldown: 0
cod:
  morph-time: 0
  morph-cooldown: 0
salmon:
  morph-time: 0
  morph-cooldown: 0
tropicalfish:
  morph-time: 0
  morph-cooldown: 0
pufferfish:
  morph-time: 0
  morph-cooldown: 0
  poison: true
  ability-cooldown: 15
phantom:
  morph-time: 0
  morph-cooldown: 0
turtle:
  morph-time: 0
  morph-cooldown: 0
bee:
  morph-time: 0
  morph-cooldown: 0
strider:
  morph-time: 0
  morph-cooldown: 0
zoglin:
  morph-time: 0
  morph-cooldown: 0
hoglin:
  morph-time: 0
  morph-cooldown: 0