#Do you want a sound/particle effect to be played when a player morphs
morph-sound: true
morph-particle: true

#Do you want a sound/particle effect to be played when a player unmorphs
unmorph-sound: true
unmorph-particle: true

#Allow morphing into players? (Possibly buggy)
enable-players: false

#Should players be able to see their own disguise?
viewSelfDisguise: true

#Should players be able to change if they view their disguises?
canChangeView: true

#When morphed as a mob do any other mobs of the same type ignore you
#e.g Morphed as a zombie means you don't get attacked by zombies
ignoreMobsWhenMorphed: true

#What worlds do you want this plugin enabled in?
#use <all> to enable in all worlds
enabled-worlds:
- world
- world_nether
- world_the_end

#Reset all of the players morphs when they die
death-reset-all: false
#Reset only the morph they died as
death-reset-current: true

#When a player kills a morphed player, should they get the morph?
steal-morphs: true

#Enable morph power for flying
morph-power: true
#How fast morph power is used per second of flying
morphPower-use: 1
#How fast morph power is regained per second of not flying
morphPower-regain: 1

#The radius /morph near looks at
near-radius: 10

#Hand swap menu status
swapMenu: true
#Only open the menu when there is nothing in the players main hand?
onlyIfEmptyHand: false

#Abilities Configuration
#
#morph-cooldown is how often you can morph back into the mob after unmorphing from that particular mob
#ability-cooldown is the cooldown on the given ability of the mob
#
#Enable flying?
flying: true

horse:
  morph-cooldown: 0
  speed: true
wolf:
  morph-cooldown: 0
ocelot:
  morph-cooldown: 0
  speed: true
cow:
  morph-cooldown: 0
pig:
  morph-cooldown: 0
wither_skeleton:
  morph-cooldown: 0
  ability-cooldown: 0
bat:
  morph-cooldown: 0
blaze:
  morph-cooldown: 0
  fire: true
  ability-cooldown: 5
cave_spider:
  morph-cooldown: 0
  spider-climb: true
  ability-cooldown: 0
chicken:
  morph-cooldown: 0
  egg: true
  ability-cooldown: 120
creeper:
  morph-cooldown: 0
  explosion: true
  explosion-damage: false
enderman:
  morph-cooldown: 0
  teleport: true
  ability-cooldown: 5
endermite:
  morph-cooldown: 0
ghast:
  morph-cooldown: 0
  fireball: true
  ability-cooldown: 5
guardian:
  morph-cooldown: 0
iron_golem:
  morph-cooldown: 0
  strength: true
magma_cube:
  morph-cooldown: 0
mushroom_cow:
  morph-cooldown: 0
pig_zombie:
  morph-cooldown: 0
  eat: true
  speed: true
sheep:
  morph-cooldown: 0
silverfish:
  morph-cooldown: 0
skeleton:
  morph-cooldown: 0
  shoot: true
slime:
  morph-cooldown: 0
  jump-boost: true
  split: true
snowman:
  morph-cooldown: 0
  snow: true
  shoot: true
  ability-cooldown: 0
spider:
  morph-cooldown: 0
  spider-climb: true
  web: true
  #Remove spider webs after they are shot?
  removeSpiderWeb: true
  #How long (seconds) should webs stay for before despawning
  spiderWebRemove: 30
  ability-cooldown: 0
squid:
  morph-cooldown: 0
  waterbreathing: true
villager:
  morph-cooldown: 0
witch:
  morph-cooldown: 0
wither:
  morph-cooldown: 0
llama:
  morph-cooldown: 0
  spit: true
  ability-cooldown: 0
vex:
  morph-cooldown: 0
  phase: true
  #The amount of blocks vex can phase through
  max-layers: 2
  ability-cooldown: 30
vindicator:
  morph-cooldown: 0
evoker:
  morph-cooldown: 0
  attack: true
  spawnVex: true
  attack-cooldown: 5
  spawnVex-cooldown: 30
zombie:
  morph-cooldown: 0
  eat: true
rabbit:
  morph-cooldown: 0
  jump-boost: true
giant:
  enabled: true
  morph-cooldown: 0
  throw: true
  #This increases how high giants can throw people
  force: 2
  #Enables the giant to 'throw' blocks as he walks
  #NOTE: This might cause random blocks to be placed/broken if enabled
  giant-walk-throw: false
  ability-cooldown: 0
enderdragon:
  enabled: true
  morph-cooldown: 0
  fireball: true
  ability-cooldown: 0
mule:
  morph-cooldown: 0
donkey:
  morph-cooldown: 0
zombie_villager:
  morph-cooldown: 0
parrot:
  morph-cooldown: 0
illusioner:
  morph-cooldown: 0
  ability-cooldown: 0
stray:
  morph-cooldown: 0
  slow: true
  ability-cooldown: 0
husk:
  morph-cooldown: 0
  hunger: true

disableHealthSystem: false
checkForUpdates: true
debug: false
stats: true
